---
# The directory (on the source server) to scan for files to transfer
src_dir: "/home/vagrant/receiving/"

# Set to true to move files (on the source server) to a different
# directory after a successful transfer, false otherwise
move_files_after_successful_transfer: true

# The directory (on the source server) to move files to after successful
# transfer
succesful_transfer_dir: "/tmp/"

# Prunes empty subdirectories (on the source server) in src_dir
prune_empty_subdirectories: true

# The log file to use. Use "STDOUT" for standard out
logger.logfile: "STDOUT"

# The log level to use, i.e.,
# Logger::DEBUG, Logger::INFO, WARN, Logger::ERROR, Logger::FATAL, Logger::UNKNOWN
logger.level: "Logger::DEBUG"

# Array of destination servers the files should be transferred to
destination_servers:
#  - server: "192.168.41.105"
#    directory: "/tmp/"

  - server: "192.168.41.100"
    username: vagrant
    directory: "/tmp/"
    disable_move_on_failure: true

smtp_server:
    # The IP address/hostname of the SMTP server
    address: localhost
    # The port to contact the SMTP server
    port: 25
    # The domain to use with the SMTP server
    domain:
    # The authentication scheme to use, typicially ":plain", ":login", or
    # ":cram_md5"
    authentication:
    # The username to send for authentication
    user_name:
    # The password to send for authentication
    password:
    # If true, mail will be "sent" to a logfile, instead of actually being sent
    debug: true

mail:
  # The "from" address to use in emails
  from: test@example.com
  # The "to" address to send emails to
  to: test@example.com